export const SET_DATA = 'SET_DATA'
export const SET_SORT_BY = 'SET_SORT_BY'
export const SET_SORT_ASCENDENCE = 'SET_SORT_ASCENDENCE'
export const SET_MODE = 'SET_MODE'
export const SET_FILTER = 'SET_FILTER'